<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Nodify\Nodify.csproj" />
    <ProjectReference Include="..\Nodify.Shared\Nodify.Shared.csproj" />
  </ItemGroup>

</Project>