<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);Avalonia</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);Avalonia</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Nodify\Connections\Events\ConnectionEventArgs.cs" Link="Connections\Events\ConnectionEventArgs.cs" />
    <Compile Include="..\..\Nodify\Connectors\Events\ConnectorEventArgs.cs" Link="Connectors\Events\ConnectorEventArgs.cs" />
    <Compile Include="..\..\Nodify\Connectors\Events\PendingConnectionEventArgs.cs" Link="Connectors\Events\PendingConnectionEventArgs.cs" />
    <Compile Include="..\..\Nodify\Utilities\BoxValue.cs" Link="Utilities\BoxValue.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.7" />
  </ItemGroup>

</Project>
